### ISSUE TITLE
Query about polyps detection and localization

### ISSUE THREAD

**Issue by ahmedeqbal** [DebeshJha/ColonSegNet#1]
Thanks for sharing such a nice code !

But unfortunately, I never found **detection and localization** code? After the training process, I want to compute **AP, AP25, AP50, AP75** and visualize the polyp regions with a **bounding box**. Can you share it? 

I would appreciate it!

Best regards

**Comment by DebeshJha** [comment]
https://github.com/sharibox/EAD2019/tree/master/fileFormatConverters
